function project = heat_diffusion_config()
%HEAT_DIFFUSION_CONFIG 声明项目发布资料。

    thisFile = [mfilename('fullpath'), '.m'];
    sourceDir = fileparts(thisFile);
    project = struct( ...
        'id', 'heat-diffusion', ...
        'title', 'Heat Diffusion Lab', ...
        'sourceDir', sourceDir, ...
        'sourceFiles', {{ ...
            'heat_diffusion_main.m', ...
            'heat_diffusion_config.m', ...
            'build_heat_diffusion.m', ...
            'initial_temperature_demo.m', ...
            'simulate_heat_diffusion_demo.m', ...
            'evaluate_heat_stability_demo.m', ...
            'create_heat_figures.m'}}, ...
        'buildFunction', @build_heat_diffusion);
end
