function project = queue_simulation_config()
%QUEUE_SIMULATION_CONFIG 声明项目发布资料。

    thisFile = [mfilename('fullpath'), '.m'];
    sourceDir = fileparts(thisFile);
    project = struct( ...
        'id', 'queue-simulation', ...
        'title', 'Queue Simulation Lab', ...
        'sourceDir', sourceDir, ...
        'sourceFiles', {{ ...
            'queue_simulation_main.m', ...
            'queue_simulation_config.m', ...
            'build_queue_simulation.m', ...
            'simulate_queue_demo.m', ...
            'summarize_queue_demo.m', ...
            'create_queue_figures.m'}}, ...
        'buildFunction', @build_queue_simulation);
end
