function paths = demo_project_paths(projectId)
%DEMO_PROJECT_PATHS 返回与当前工作目录无关的发布路径。

    if nargin < 1 || ~ischar(projectId) || ...
            isempty(regexp(projectId, '^[a-z0-9]+(?:-[a-z0-9]+)*$', 'once'))
        error('Demo:InvalidProjectId', ...
            'Project ID must use lowercase letters, numbers, and hyphens.');
    end

    thisFile = [mfilename('fullpath'), '.m'];
    matlabDir = fileparts(thisFile);
    repositoryRoot = fileparts(matlabDir);
    docsDir = fullfile(repositoryRoot, 'docs');
    contentRoot = fullfile(docsDir, 'content');
    projectsRoot = fullfile(contentRoot, 'projects');
    projectContentDir = fullfile(projectsRoot, projectId);

    paths = struct( ...
        'matlabDir', matlabDir, ...
        'repositoryRoot', repositoryRoot, ...
        'docsDir', docsDir, ...
        'contentRoot', contentRoot, ...
        'projectsRoot', projectsRoot, ...
        'projectContentDir', projectContentDir, ...
        'dataDir', fullfile(projectContentDir, 'data'), ...
        'plotsDir', fullfile(projectContentDir, 'plots'), ...
        'codeDir', fullfile(projectContentDir, 'code'), ...
        'manifestPath', fullfile(projectContentDir, 'manifest.json'), ...
        'catalogPath', fullfile(contentRoot, 'catalog.json'));
end
