function bundle = build_signal_denoising()
%BUILD_SIGNAL_DENOISING 构建结果数据与四张案例图表。

    settings = struct( ...
        'sampleRate', 200, ...
        'durationSeconds', 10, ...
        'noiseStandardDeviation', 0.55, ...
        'impulseCount', 14, ...
        'randomSeed', 20260917, ...
        'windowSizes', [1, 3, 5, 7, 9, 11, 15, 21, 31, 41, 61]);

    signalData = signal_denoising_generate_signal(settings);
    [windowResults, filteredSignals, bestIndex, evaluationMask] = ...
        signal_denoising_evaluate_windows( ...
            signalData.cleanSignal, signalData.observedSignal, ...
            settings.windowSizes);

    bestFiltered = filteredSignals(:, bestIndex);
    inputError = signalData.observedSignal(evaluationMask) - ...
        signalData.cleanSignal(evaluationMask);
    outputError = bestFiltered(evaluationMask) - ...
        signalData.cleanSignal(evaluationMask);
    reference = signalData.cleanSignal(evaluationMask);

    metrics = struct();
    metrics.inputSNR = roundTo(10 * log10( ...
        sum(reference .^ 2) / sum(inputError .^ 2)), 3);
    metrics.outputSNR = roundTo(10 * log10( ...
        sum(reference .^ 2) / sum(outputError .^ 2)), 3);
    metrics.rawRMSE = roundTo(sqrt(mean(inputError .^ 2)), 4);
    metrics.filteredRMSE = roundTo(sqrt(mean(outputError .^ 2)), 4);
    metrics.bestWindow = windowResults(bestIndex).window;

    % 统一结果精度，便于网页展示与版本比较。
    for index = 1:numel(windowResults)
        windowResults(index).rmse = roundTo(windowResults(index).rmse, 4);
        windowResults(index).outputSNR = ...
            roundTo(windowResults(index).outputSNR, 3);
    end

    results = struct();
    results.metrics = metrics;
    results.windows = windowResults;
    results.configuration = struct( ...
        'sampleRate', settings.sampleRate, ...
        'durationSeconds', settings.durationSeconds, ...
        'noiseStandardDeviation', settings.noiseStandardDeviation, ...
        'impulseCount', settings.impulseCount);

    bundle = struct();
    bundle.results = results;
    bundle.figures = signal_denoising_create_figures( ...
        signalData, bestFiltered, windowResults, bestIndex);
end

function value = roundTo(value, digits)
%ROUNDTO 兼容旧版本 MATLAB 的小数位取整。
    scale = 10 ^ digits;
    value = round(value * scale) / scale;
end
