function project = signal_denoising_config()
%SIGNAL_DENOISING_CONFIG 返回公共发布器需要的项目配置。

    configFile = [mfilename('fullpath'), '.m'];
    sourceDir = fileparts(configFile);

    project = struct();
    project.id = 'signal-denoising';
    project.title = 'Signal Denoising Lab';
    project.sourceDir = sourceDir;
    project.sourceFiles = { ...
        'signal_denoising_main.m', ...
        'signal_denoising_config.m', ...
        'build_signal_denoising.m', ...
        'signal_denoising_generate_signal.m', ...
        'signal_denoising_moving_average.m', ...
        'signal_denoising_compute_spectrum.m', ...
        'signal_denoising_evaluate_windows.m', ...
        'signal_denoising_create_figures.m'};
    project.buildFunction = @build_signal_denoising;
end
